### ISSUE TITLE
Do not fail on every non-slash command

### ISSUE THREAD

**Issue by MOZGIII** [xt0rted/slash-command-action#124]
Currently, the task fails for every non-slash command, making the regular discussions on the PR impossible due to email spam from Github Actions.
Can we figure out a workaround for it?

**Comment by xt0rted** [comment]
Hi @MOZGIII thanks for bringing this up.

It's missing from the sample in the readme, but there's a setting you can add to job steps called [`continue-on-error`](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) that will prevent the workflow from failing.

You can use this along with an if condition on the remaining steps so they only run when the command is provided. It would look something like this:

```yml
jobs:
  check_comments:
    name: Check comments for /lint
      steps:
        - uses: xt0rted/slash-command-action@v1
          id: command
          continue-on-error: true
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            command: lint

        - run: echo "Runs on all /lint commands"
          if: steps.command.outputs.command-name

        - run: echo "Runs only on /lint js command"
          if: steps.command.outputs.command-name && steps.command.outputs.command-arguments == 'js'

        - run: echo "Runs only on /lint css command"
          if: steps.command.outputs.command-name && steps.command.outputs.command-arguments == 'css'

        - run: echo "This step always runs"
```

Making the change you proposed in #123 will remove the need for `continue-on-error`. I'm also working on an update that adds a new out parameter called `has-command` that can be used for these types of checks.
