### ISSUE TITLE
Get branch ref for pr comments and set it as an output value

### ISSUE THREAD

**Issue by xt0rted** [xt0rted/slash-command-action#20]
When the `issue_comment` event is triggered on a PR the action payload is for the `default` branch not the PR branch. Because of this we need to do some magic to get the PR branch info and pass it along to the next action.

The idea is to do something like so:

```yaml
on:
  issue_comment:
    types: created

jobs:
  lint:
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: lint

      - name: Checkout Repo
        uses: actions/checkout@v1
        with:
          ref: ${{ steps.command.outputs.branch-ref }}
```

**Comment by xt0rted** [comment]
This functionality was built out in a separate action called [xt0rted/pull-request-comment-branch](https://github.com/xt0rted/pull-request-comment-branch). It can be used along with this action like so:

```yml
on:
  issue_comment:
    types: created

jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: dotnet
          reaction-type: "eyes"

      - name: Get PR Branch
        if: steps.command.outputs.command-arguments == 'format'
        id: comment-branch
        uses: xt0rted/pull-request-comment-branch@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Repo
        if: success()
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.comment-branch.outputs.ref }}
```
